---
name: CI

on:
  push:
    branches:
      - master

jobs:
  helmbuild:
    name: Update Chart Repo
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          url: https://nolte.github.io/helm-charts/
      - name: update index.yaml
        uses: nolte/github-action/helm/repo_index_update@master
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes" -a
          git push origin master