name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  integrate_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

      - name: Run shasum
        id: load_release_informations
        uses: nolte/github-action/github/getRelease@feature/shasum
        with:
          repo: "${{ github.event.client_payload.repository }}"
          releaseId: "${{ github.event.client_payload.releaseId }}"
      - name: Create Pull Request
        if: success()
        run: |      
          echo '${{ steps.load_release_informations.outputs.url }}'


#      - uses: actions/checkout@v2
#        if: github.event.action == 'helm_release'
#      - name: wget
#        uses: wei/wget@v1
#        if: github.event.action == 'helm_release'
#        with:
#          args: -P ./chart-repo/ ${{ github.event.client_payload.chart_download_url }} 
#
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v2
#        if: success()
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          title: "New Chart Release"
