name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  integrate_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - uses: actions/github-script@0.4.0
        if: github.event.action == 'helm_release'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const owner = context.payload.client_payload.repository.split("/")[0]
            const repo = context.payload.client_payload.repository.split("/")[0]
            const release = await github.repos.getRelease({
              owner,
              repo,
              context.payload.client_payload.releaseId
            })
            console.log(release)
            release
#      - uses: actions/checkout@v2
#        if: github.event.action == 'helm_release'
#      - name: wget
#        uses: wei/wget@v1
#        if: github.event.action == 'helm_release'
#        with:
#          args: -P ./chart-repo/ ${{ github.event.client_payload.chart_download_url }} 
#
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v2
#        if: success()
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          title: "New Chart Release"
